package com.kayque.compensa.purchase.score.service;

public enum PurchaseScoreCriterion {

    PLANNED_PURCHASE,
    UNPLANNED_PURCHASE,

    NECESSITY_MOTIVATION,
    IMPULSE_MOTIVATION,

    URGENT_PURCHASE,

    HAS_NO_ALTERNATIVE,
    HAS_ALTERNATIVE,

    LOW_BUDGET_IMPACT,
    MODERATE_BUDGET_IMPACT,
    HIGH_BUDGET_IMPACT,
    CRITICAL_BUDGET_IMPACT,

    LOW_WORK_TIME,
    HIGH_WORK_TIME,
    CRITICAL_WORK_TIME,

    HIGH_ADDITIONAL_TIME,

    LOW_GOAL_IMPACT,
    HIGH_GOAL_IMPACT,
    CRITICAL_GOAL_IMPACT,

    MONTHLY_FREQUENCY,
    WEEKLY_FREQUENCY,
    DAILY_FREQUENCY,

    HIGH_ANNUAL_PROJECTION,
    CRITICAL_ANNUAL_PROJECTION
}